# Generated by Django 4.2.16 on 2024-11-27 16:34

import badge.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Waste Reduction', 'Waste reduction'), ('Energy Saving', 'Energy saving')], default='Transport', max_length=20)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('actions_required', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(default=badge.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
