# Generated by Django 4.2.16 on 2024-11-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badge_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='creator',
            new_name='employee',
        ),
    ]
