# Generated by Django 4.2.16 on 2024-11-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_create_category_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
