# Generated by Django 4.2.16 on 2024-11-28 09:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile/profile_footprint.webp', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[200, None], upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='image_alt',
            field=models.CharField(default='profile image', max_length=100),
        ),
    ]
