# Generated by Django 4.2.16 on 2024-11-28 09:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0003_alter_employeeprofile_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='/profiles/profile_footprint_jowwx7.png', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[200, None], upload_to='profiles/'),
        ),
    ]
