# Generated by Django 4.2.16 on 2024-11-27 09:59

import co2measures.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('co2measures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='measure',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Waste Reduction', 'Waste reduction'), ('Energy Saving', 'Energy saving')], default='Transport', max_length=20),
        ),
        migrations.AddField(
            model_name='measure',
            name='creator',
            field=models.ForeignKey(default=co2measures.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measure',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
